// LombokAlgoritma — Main Entry Point
// SPDX-License-Identifier: Apache-2.0 OR MIT — @codinglombok
// Zero external dependencies. Algorithm counts: see README (generated by scripts/count_algorithms.ts).

export * as Core from './core/index.js';
export { AlgoError, type ErrorCode } from './core/errors.js';
export * as Sort from './sort/index.js';
export * as Search from './search/index.js';
export * as Math from './math/index.js';
export * as StringAlgo from './string/index.js';
export * as DataStructure from './datastructure/index.js';
export * as ML from './ml/index.js';

// Commonly used direct exports
export { quicksort, timsort, mergesort, heapsort, sort } from './sort/index.js';
export { binarySearch, lowerBound, upperBound, interpolationSearch } from './search/index.js';
export { levenshtein, kmpSearch, AhoCorasick } from './string/index.js';
export { BloomFilter, HyperLogLog, DisjointSet } from './datastructure/index.js';
export { cosineSimilarity, l2Distance, dotProduct, normalize, batchCosine } from './ml/index.js';

// Graph module
export * as Graph from './graph/index.js';
export {
  dijkstra,
  bfs,
  dfs,
  floydWarshall,
  topologicalSort,
  kruskal,
  pageRank,
  aStar,
  bellmanFord,
  prim,
  tarjanScc,
  dinic,
  bipartiteMatching,
} from './graph/index.js';

// Additional modules
export * as Compression from './compression/index.js';
export * as Geometry from './geometry/index.js';
export * as Concurrent from './concurrent/index.js';
export * as Hardware from './hardware/index.js';
