[toolchain]
channel = "1.75.0"
components = ["rustfmt", "clippy", "rust-src"]
targets = [
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "wasm32-unknown-unknown",
  "thumbv7em-none-eabihf",
]
profile = "minimal"
