# LombokAlgoritma — golangci-lint v2 configuration (run from go/: golangci-lint run ./...)
# SPDX-License-Identifier: Apache-2.0 OR MIT
# G115: integer conversions are range-checked explicitly in the code.
version: "2"
run:
  go: "1.21"
linters:
  enable:
    - bodyclose
    - exhaustive
    - gosec
    - misspell
    - noctx
    - prealloc
    - revive
    - unparam
  settings:
    gosec:
      excludes:
        - G115
    revive:
      rules:
        - name: exported
        - name: var-naming
        - name: package-comments
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: increment-decrement
        - name: range
        - name: time-equal
        - name: unexported-return
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - vendor
      - third_party$
      - builtin$
      - examples$
