// LombokAlgoritma — count algorithms and ports from the source tree
// SPDX-License-Identifier: Apache-2.0 OR MIT — @codinglombok
//
// Every number in the README "Status" section is produced by this script, so it can never
// drift from the code.
//
//   npx tsx scripts/count_algorithms.ts            # print Markdown to stdout
//   npx tsx scripts/count_algorithms.ts --json     # machine-readable
//   npx tsx scripts/count_algorithms.ts --write    # rewrite README.md between the markers
//   npx tsx scripts/count_algorithms.ts --check    # exit 1 if README.md is stale (CI)
//
// Definitions (normative for the README):
// * algorithm  = an exported top-level `function` or `class` of the TypeScript reference under
//                typescript/src/<module>/ (module ∉ {core, hardware}; helper files types.ts/bytes.ts excluded).
// * port API   = a public top-level symbol of a port, found with the per-language pattern below.
// * groups     = vector groups named in the port's runner sources
// * status     = ✅ the runner names every group of vectors/lombokalgoritma-vectors-v1.json
//                🟡 the port has its own tests but no shared-vector runner
//                —  no tests in the port

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const START = '<!-- counts:start (generated by scripts/count_algorithms.ts — do not edit) -->';
const END = '<!-- counts:end -->';

interface PortSpec {
  lang: string;
  src: string[];
  ext: string[];
  pattern: RegExp;
  tests: string[];
  /** Runner sources: the groups named there are the groups the port implements. */
  runner: string[];
  exclude?: RegExp;
}

/** Shared types / byte helpers, not algorithms (graph/types.ts, string/hash/bytes.ts, geometry/types.ts). */
const HELPER_FILE = /[/\\](types|bytes)\.ts$/;
const VECTOR_FILE = 'vectors/lombokalgoritma-vectors-v1.json';
const VECTOR_MARKER = /lombokalgoritma-vectors-v1/;

const PORTS: PortSpec[] = [
  {
    lang: 'TypeScript',
    src: ['typescript/src'],
    ext: ['.ts'],
    pattern: /^export (?:async )?(?:function\*?|class) ([A-Za-z_$][\w$]*)/gm,
    tests: ['typescript/tests'],
    runner: ['typescript/tests/vectors'],
    exclude: /[/\\](core|hardware)[/\\]/,
  },
  {
    lang: 'Rust',
    src: ['rust/lombokalgoritma/src'],
    ext: ['.rs'],
    pattern: /^\s*pub fn ([a-z_][\w]*)/gm,
    tests: ['rust/lombokalgoritma/src', 'rust/lombokalgoritma/tests', 'rust/lombokalgoritma-vectors/tests'],
    runner: ['rust/lombokalgoritma-vectors/src'],
    exclude: /[/\\](core|num\.rs)/,
  },
  {
    lang: 'Go',
    src: ['go'],
    ext: ['.go'],
    pattern: /^func ([A-Z]\w*)/gm,
    tests: ['go'],
    runner: ['go/internal/vectors'],
    exclude: /(_test\.go$|[/\\](internal|cmd)[/\\])/,
  },
  {
    lang: 'Python',
    src: ['python/lombokalgoritma'],
    ext: ['.py'],
    pattern: /^(?:def|class) ([A-Za-z]\w*)/gm,
    tests: ['python/tests'],
    runner: ['python/lombokalgoritma/_vectors.py'],
    exclude: /[/\\]_\w+\.py$/,
  },
  {
    lang: 'PHP',
    src: ['php/src'],
    ext: ['.php'],
    pattern: /^\s*public (?:static )?function ([a-z]\w*)/gm,
    tests: ['php/tests'],
    runner: ['php/src/LombokAlgoritma/Vectors'],
    exclude: /[/\\]Vectors[/\\]/,
  },
  {
    lang: 'Java',
    src: ['java/src/main'],
    ext: ['.java'],
    pattern: /^\s*public static (?:<[^>]+> )?[\w<>[\], ]+ (\w+)\(/gm,
    tests: ['java/src/test'],
    runner: [],
  },
  {
    lang: 'Kotlin',
    src: ['kotlin/src/commonMain'],
    ext: ['.kt'],
    pattern: /^fun (?:<[^>]+> )?(?:[\w<>]+\.)?(\w+)\(/gm,
    tests: ['kotlin/src/commonTest'],
    runner: [],
  },
  {
    lang: 'C#',
    src: ['csharp/src'],
    ext: ['.cs'],
    pattern: /^\s*public static [\w<>[\], ?]+ (\w+)(?:<[^>]+>)?\(/gm,
    tests: ['csharp/tests'],
    runner: [],
  },
  {
    lang: 'C++',
    src: ['cpp/include'],
    ext: ['.hpp'],
    pattern: /^(?:inline |constexpr )?(?:std::)?[\w:<>]+(?:<[^>]*>)? ([a-z_]\w*)\(/gm,
    tests: ['cpp/tests'],
    runner: [],
  },
  {
    lang: 'Swift',
    src: ['swift/Sources'],
    ext: ['.swift'],
    pattern: /^\s*public (?:static )?func (\w+)/gm,
    tests: ['swift/Tests'],
    runner: [],
  },
  {
    lang: 'Perl',
    src: ['perl/lib'],
    ext: ['.pm'],
    pattern: /^sub ([a-z]\w*)/gm,
    tests: ['perl/t'],
    runner: [],
  },
  {
    lang: 'SQL',
    src: ['sql'],
    ext: ['.sql'],
    pattern: /^CREATE (?:OR REPLACE )?FUNCTION (?:[\w.]+\.)?"?(\w+)"?/gim,
    tests: ['sql/tests'],
    runner: [],
  },
];

/** Vector group names, e.g. "graph.dijkstra". */
function vectorGroups(): string[] {
  const doc = JSON.parse(readFileSync(join(ROOT, VECTOR_FILE), 'utf8')) as { groups: Record<string, unknown> };
  return Object.keys(doc.groups).sort();
}

function walk(dir: string, ext: string[]): string[] {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  const out: string[] = [];
  const stack = [abs];
  while (stack.length > 0) {
    const d = stack.pop() as string;
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (name === 'node_modules' || name === 'target' || name.startsWith('.')) continue;
      if (statSync(p).isDirectory()) stack.push(p);
      else if (ext.some((e) => name.endsWith(e))) out.push(p);
    }
  }
  return out.sort();
}

function symbols(files: string[], pattern: RegExp, exclude?: RegExp): Set<string> {
  const found = new Set<string>();
  for (const f of files) {
    if (exclude?.test(f) === true) continue;
    const text = readFileSync(f, 'utf8');
    for (const m of text.matchAll(pattern)) if (m[1] !== undefined) found.add(m[1]);
  }
  return found;
}

export interface PortReport {
  lang: string;
  api: number;
  tests: number;
  /** Vector groups named in the port's runner sources. */
  groups: number;
  status: '✅' | '🟡' | '—';
}

export interface Report {
  algorithms: number;
  modules: Record<string, string[]>;
  languages: number;
  vectorGroups: number;
  ports: PortReport[];
}

export function buildReport(): Report {
  const ts = PORTS[0] as PortSpec;
  const srcRoot = join(ROOT, 'typescript', 'src');
  const modules: Record<string, string[]> = {};
  let algorithms = 0;
  for (const f of walk('typescript/src', ['.ts'])) {
    const rel = relative(srcRoot, f).split(sep);
    const mod = rel.length > 1 ? (rel[0] as string) : '(root)';
    if (mod === 'core' || mod === 'hardware' || mod === '(root)') continue;
    if (HELPER_FILE.test(f)) continue;
    const names = [...readFileSync(f, 'utf8').matchAll(ts.pattern)].map((m) => m[1] as string);
    modules[mod] = [...(modules[mod] ?? []), ...names].sort((a, b) => a.localeCompare(b));
    algorithms += names.length;
  }

  const groups = vectorGroups();
  const ports: PortReport[] = PORTS.map((p) => {
    const files = p.src.flatMap((s) => walk(s, p.ext));
    const api = symbols(files, p.pattern, p.exclude).size;
    const testFiles = p.tests.flatMap((t) => walk(t, [...p.ext, '.t', '.test.ts', '.cpp', '.kt', '.swift']));
    const testCount = testFiles.filter((f) => /test|spec|[/\\]t[/\\]/i.test(f) || f.endsWith('.rs')).length;
    const runnerText = p.runner
      .flatMap((r) => (r.endsWith(p.ext[0] as string) ? [join(ROOT, r)] : walk(r, p.ext)))
      .filter((f) => existsSync(f))
      .map((f) => readFileSync(f, 'utf8'))
      .join('\n');
    const covered = groups.filter((g) => runnerText.includes(`'${g}'`) || runnerText.includes(`"${g}"`)).length;
    const hasRunner = VECTOR_MARKER.test(runnerText) || covered > 0;
    const status: PortReport['status'] =
      hasRunner && covered === groups.length ? '✅' : testCount > 0 ? '🟡' : '—';
    return { lang: p.lang, api, tests: testCount, groups: covered, status };
  });

  return {
    algorithms,
    modules,
    languages: ports.filter((p) => p.api > 0).length,
    vectorGroups: groups.length,
    ports,
  };
}

export function toMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(
    `**${r.algorithms} algorithms** in the TypeScript reference across ${Object.keys(r.modules).length} modules, **${r.languages} languages** with code, **${r.vectorGroups} shared vector groups**.`,
  );
  lines.push('');
  lines.push('| Module | # | Exported algorithms / structures |', '|---|---:|---|');
  for (const [m, names] of Object.entries(r.modules).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`| \`${m}\` | ${names.length} | ${names.map((n) => `\`${n}\``).join(', ')} |`);
  }
  lines.push('');
  lines.push('| Port | Public API symbols | Vector groups | Status |', '|---|---:|---:|:---:|');
  for (const p of r.ports) {
    lines.push(`| ${p.lang} | ${p.api} | ${p.groups > 0 ? `${p.groups}/${r.vectorGroups}` : '—'} | ${p.status} |`);
  }
  lines.push('');
  lines.push(
    '✅ runner covers every group of `vectors/lombokalgoritma-vectors-v1.json` (CI checks byte-identical output) · 🟡 partial — own tests only · — no tests',
  );
  return lines.join('\n');
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  const report = buildReport();
  if (args.has('--json')) {
    process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
    return;
  }
  const md = toMarkdown(report);
  if (!args.has('--write') && !args.has('--check')) {
    process.stdout.write(`${md}\n`);
    return;
  }
  const readmePath = join(ROOT, 'README.md');
  const readme = readFileSync(readmePath, 'utf8');
  const a = readme.indexOf(START);
  const b = readme.indexOf(END);
  if (a < 0 || b < a) throw new Error('README.md is missing the counts markers');
  const next = `${readme.slice(0, a + START.length)}\n${md}\n${readme.slice(b)}`;
  if (args.has('--check')) {
    if (next !== readme) {
      process.stderr.write(
        'README.md counts are stale — run: npx tsx scripts/count_algorithms.ts --write\n',
      );
      process.exit(1);
    }
    return;
  }
  writeFileSync(readmePath, next);
}

main();
