// LombokAlgoritma — count algorithms and ports from the source tree
// SPDX-License-Identifier: Apache-2.0 OR MIT — @codinglombok
//
// Every number in the README "Status" section is produced by this script, so it can never
// drift from the code.
//
//   npx tsx scripts/count_algorithms.ts            # print Markdown to stdout
//   npx tsx scripts/count_algorithms.ts --json     # machine-readable
//   npx tsx scripts/count_algorithms.ts --write    # rewrite README.md between the markers
//   npx tsx scripts/count_algorithms.ts --check    # exit 1 if README.md is stale (CI)
//
// Definitions (normative for the README):
// * algorithm  = an exported top-level `function` or `class` of the TypeScript reference under
//                src/<module>/ (module ∉ {core, hardware}); deprecated crypto is reported apart.
// * port API   = a public top-level symbol of a port, found with the per-language pattern below.
// * status     = ✅ the port has a shared-vector runner (a test that reads the vectors/ files)
//                🟡 the port has its own tests but no shared-vector runner
//                —  no tests in the port

import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs';
import { join, relative, sep } from 'node:path';

const ROOT = join(import.meta.dirname, '..');
const START = '<!-- counts:start (generated by scripts/count_algorithms.ts — do not edit) -->';
const END = '<!-- counts:end -->';

interface PortSpec {
  lang: string;
  src: string[];
  ext: string[];
  pattern: RegExp;
  tests: string[];
  /** A test file counts as a vector runner when it mentions this path fragment. */
  vectorMarker: RegExp;
  exclude?: RegExp;
}

const VECTOR_MARKER = /(tests[/\\]vectors|vectors[/\\]lombokalgoritma-vectors)/;

const PORTS: PortSpec[] = [
  {
    lang: 'TypeScript',
    src: ['src'],
    ext: ['.ts'],
    pattern: /^export (?:async )?(?:function\*?|class) ([A-Za-z_$][\w$]*)/gm,
    tests: ['tests/core'],
    vectorMarker: /['"]\.\.['"],\s*['"]vectors['"]|tests[/\\]vectors/,
    exclude: /[/\\](core|hardware|crypto)[/\\]/,
  },
  {
    lang: 'Rust',
    src: ['rust/lombokalgoritma/src'],
    ext: ['.rs'],
    pattern: /^\s*pub fn ([a-z_][\w]*)/gm,
    tests: ['rust/lombokalgoritma/src', 'rust/lombokalgoritma/tests'],
    vectorMarker: VECTOR_MARKER,
    exclude: /[/\\]core[/\\]/,
  },
  {
    lang: 'Go',
    src: ['go'],
    ext: ['.go'],
    pattern: /^func ([A-Z]\w*)/gm,
    tests: ['go'],
    vectorMarker: VECTOR_MARKER,
    exclude: /_test\.go$/,
  },
  {
    lang: 'Python',
    src: ['ports/python/lombokalgoritma'],
    ext: ['.py'],
    pattern: /^(?:def|class) ([A-Za-z]\w*)/gm,
    tests: ['ports/python/tests'],
    vectorMarker: VECTOR_MARKER,
    exclude: /[/\\]_\w+\.py$/,
  },
  {
    lang: 'PHP',
    src: ['ports/php/src'],
    ext: ['.php'],
    pattern: /^\s*public static function ([A-Za-z]\w*)/gm,
    tests: ['ports/php/tests'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'Java',
    src: ['ports/java/src/main'],
    ext: ['.java'],
    pattern: /^\s*public static (?:<[^>]+> )?[\w<>[\], ]+ (\w+)\(/gm,
    tests: ['ports/java/src/test'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'Kotlin',
    src: ['ports/kotlin/src/commonMain'],
    ext: ['.kt'],
    pattern: /^fun (?:<[^>]+> )?(?:[\w<>]+\.)?(\w+)\(/gm,
    tests: ['ports/kotlin/src/commonTest'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'C#',
    src: ['ports/csharp/src'],
    ext: ['.cs'],
    pattern: /^\s*public static [\w<>[\], ?]+ (\w+)(?:<[^>]+>)?\(/gm,
    tests: ['ports/csharp/tests'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'C++',
    src: ['ports/cpp/include'],
    ext: ['.hpp'],
    pattern: /^(?:inline |constexpr )?(?:std::)?[\w:<>]+(?:<[^>]*>)? ([a-z_]\w*)\(/gm,
    tests: ['ports/cpp/tests'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'Swift',
    src: ['ports/swift/Sources'],
    ext: ['.swift'],
    pattern: /^\s*public (?:static )?func (\w+)/gm,
    tests: ['ports/swift/Tests'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'Perl',
    src: ['ports/perl/lib'],
    ext: ['.pm'],
    pattern: /^sub ([a-z]\w*)/gm,
    tests: ['ports/perl/t'],
    vectorMarker: VECTOR_MARKER,
  },
  {
    lang: 'SQL',
    src: ['ports/sql'],
    ext: ['.sql'],
    pattern: /^CREATE (?:OR REPLACE )?FUNCTION (?:[\w.]+\.)?"?(\w+)"?/gim,
    tests: ['ports/sql/tests'],
    vectorMarker: VECTOR_MARKER,
  },
];

function walk(dir: string, ext: string[]): string[] {
  const abs = join(ROOT, dir);
  if (!existsSync(abs)) return [];
  const out: string[] = [];
  const stack = [abs];
  while (stack.length > 0) {
    const d = stack.pop() as string;
    for (const name of readdirSync(d).sort()) {
      const p = join(d, name);
      if (name === 'node_modules' || name === 'target' || name.startsWith('.')) continue;
      if (statSync(p).isDirectory()) stack.push(p);
      else if (ext.some((e) => name.endsWith(e))) out.push(p);
    }
  }
  return out.sort();
}

function symbols(files: string[], pattern: RegExp, exclude?: RegExp): Set<string> {
  const found = new Set<string>();
  for (const f of files) {
    if (exclude?.test(f)) continue;
    const text = readFileSync(f, 'utf8');
    for (const m of text.matchAll(pattern)) if (m[1] !== undefined) found.add(m[1]);
  }
  return found;
}

export interface PortReport {
  lang: string;
  api: number;
  tests: number;
  status: '✅' | '🟡' | '—';
}

export interface Report {
  algorithms: number;
  deprecatedCrypto: number;
  modules: Record<string, string[]>;
  languages: number;
  ports: PortReport[];
}

export function buildReport(): Report {
  const tsFiles = walk('src', ['.ts']);
  const modules: Record<string, string[]> = {};
  let algorithms = 0;
  let deprecatedCrypto = 0;
  const ts = PORTS[0] as PortSpec;
  for (const f of tsFiles) {
    const rel = relative(join(ROOT, 'src'), f).split(sep);
    const mod = rel.length > 1 ? (rel[0] as string) : '(root)';
    if (mod === 'core' || mod === 'hardware' || mod === 'crypto' || mod === '(root)') continue;
    const text = readFileSync(f, 'utf8');
    const deprecatedFile = /@deprecated/.test(text) && /sha256|hkdf/.test(f);
    const names = [...text.matchAll(ts.pattern)].map((m) => m[1] as string);
    if (deprecatedFile) {
      deprecatedCrypto += names.length;
      continue;
    }
    modules[mod] = [...(modules[mod] ?? []), ...names].sort((a, b) => a.localeCompare(b));
    algorithms += names.length;
  }

  const ports: PortReport[] = PORTS.map((p) => {
    const files = p.src.flatMap((s) => walk(s, p.ext));
    const api = symbols(files, p.pattern, p.exclude).size;
    const testFiles = p.tests.flatMap((t) => walk(t, [...p.ext, '.t', '.test.ts', '.cpp', '.kt', '.swift']));
    const testCount = testFiles.filter((f) => /test|spec|[/\\]t[/\\]/i.test(f) || f.endsWith('.rs')).length;
    const hasRunner = testFiles.some((f) => p.vectorMarker.test(readFileSync(f, 'utf8')));
    const status: PortReport['status'] = hasRunner ? '✅' : testCount > 0 ? '🟡' : '—';
    return { lang: p.lang, api, tests: testCount, status };
  });

  return {
    algorithms,
    deprecatedCrypto,
    modules,
    languages: ports.filter((p) => p.api > 0).length,
    ports,
  };
}

export function toMarkdown(r: Report): string {
  const lines: string[] = [];
  lines.push(
    `**${r.algorithms} algorithms** in the TypeScript reference across ${Object.keys(r.modules).length} modules, ` +
      `**${r.languages} languages** with code` +
      (r.deprecatedCrypto > 0 ? ` (+${r.deprecatedCrypto} deprecated crypto functions, removed in v0.2.0).` : '.'),
  );
  lines.push('');
  lines.push('| Module | # | Exported algorithms / structures |', '|---|---:|---|');
  for (const [m, names] of Object.entries(r.modules).sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`| \`${m}\` | ${names.length} | ${names.map((n) => `\`${n}\``).join(', ')} |`);
  }
  lines.push('');
  lines.push('| Port | Public API symbols | Status |', '|---|---:|:---:|');
  for (const p of r.ports) lines.push(`| ${p.lang} | ${p.api} | ${p.status} |`);
  lines.push('');
  lines.push(
    '✅ passes the shared test vectors · 🟡 partial — own tests only, no shared-vector runner yet · — no tests',
  );
  return lines.join('\n');
}

function main(): void {
  const args = new Set(process.argv.slice(2));
  const report = buildReport();
  if (args.has('--json')) {
    process.stdout.write(`${JSON.stringify(report, null, 2)}\n`);
    return;
  }
  const md = toMarkdown(report);
  if (!args.has('--write') && !args.has('--check')) {
    process.stdout.write(`${md}\n`);
    return;
  }
  const readmePath = join(ROOT, 'README.md');
  const readme = readFileSync(readmePath, 'utf8');
  const a = readme.indexOf(START);
  const b = readme.indexOf(END);
  if (a < 0 || b < a) throw new Error('README.md is missing the counts markers');
  const next = `${readme.slice(0, a + START.length)}\n${md}\n${readme.slice(b)}`;
  if (args.has('--check')) {
    if (next !== readme) {
      process.stderr.write('README.md counts are stale — run: npx tsx scripts/count_algorithms.ts --write\n');
      process.exit(1);
    }
    return;
  }
  writeFileSync(readmePath, next);
}

main();
